### ISSUE TITLE
Mystery Box prediction inaccurate

### ISSUE THREAD

**Issue by Mar-Veloz** [MouseyPounds/stardew-predictor#25]
I am opening mystery boxes today for the first time after getting all mastery perks, and I am finding that the predictions for the Mystery Boxes (but specifically *not* the Golden Mystery Boxes) are inaccurate.

When I open a Golden Mystery Box, what I get matches the "Golden Mystery Box With Farming Mastery Perk" column in the predictor. However, when I open a regular Mystery Box, the result does *not* match the prediction in the "Mystery Box" column in the predictor.

Without any knowledge of the game's code, my naive assumption would be that the farming mastery perk also changes the drop pool for regular mystery boxes. I've attached my [save file](https://github.com/MouseyPounds/stardew-predictor/files/14948751/Mars_371433527.json) in case that makes diagnosis easier.

**Comment by Mar-Veloz** [comment]
After doing more testing with CJB cheat menu/item spawner (and uninstalling all of my mods other than those two), it seems like the prediction is always wrong. Maybe the drop pool was changed in a recent patch?

**Comment by MouseyPounds** [comment]
I am seeing exactly the predicted output when I open boxes on your save. Make sure you have nothing extra in the URL and that the first line in the Changelog shows a Predictor version of 5.0.6 or higher. If you continue to see inaccurate results after doing so let me know and we can investigate it further.

**Comment by Mar-Veloz** [comment]
Hmm, that's weird, now I'm getting the correct prediction also. Not sure what could've been going on, since I've had https://mouseypounds.github.io/stardew-predictor/ bookmarked for almost a year now. Either way, it's working now, so I'll close this issue. Sorry for wasting your time.
