### ISSUE TITLE
Daily Luck Calendar?

### ISSUE THREAD

**Issue by neitsa** [MouseyPounds/stardew-predictor#3]
Thanks a lot for your app @MouseyPounds, it's really handy!

I was wondering how the [daily luck](https://stardewvalleywiki.com/Luck#Daily_Luck) (as reported by the fortune teller on TV) is calculated. Is the calculation made at runtime (without any way to guess it) or is it using a predefined seed passed to a `random()` function?

Put simply, my question is: Would it be technically possible to have a calendar (as for the mines or train) on **stardew-predictor** with the Daily Luck for a given day?

Thanks!

**Comment by Zamiell** [comment]
Today I noticed that the daily luck was absent from Stardew Predictor and was very surprised.
Please add this feature!

**Comment by Bla-De** [comment]
The rng for dailyLuck is affected by stepsTaken. As this varies based on play, this predictor cannot provide predicitons. This is the same for dishOfTheDay, whether an NPC sends a gift, and weather. To predict these you either need to manually track steps and enter the information into a tool, or have a mod running in game which will make this prediction for you.
