### ISSUE TITLE
Predictor not predicting very well

### ISSUE THREAD

**Issue by geekgirl101** [MouseyPounds/stardew-predictor#7]
Up until recently only the trash can predictor was failing to predict accurately what was rewarded from trash cans, but since 1.5 everything is failing to predict accurately what's going to be rewarded.

For step 25 in the geode predictor a normal geode was supposed to give 5 copper ore, instead I got a jagoite.  None of the other items came out as expected either.

The mine chest predictor predicted on floor 90 I'd get a bone sword, instead I got an obsidian sword.

Floor 96 was predicted on Spring 18 to have a monster infestation, instead it was on floor 91.

**Comment by elisamalzoni** [comment]
Same.

**Comment by agfor** [comment]
The enchant predictions seem correct for me, but the train predictions aren't.

**Comment by agfor** [comment]
Just had a witch that was correctly predicted

**Comment by agfor** [comment]
Stone Owls, Meteors, and Strange Capsules also appear to be correct.

**Comment by agfor** [comment]
Well I just had a correctly predicted train after 4 in a row that didn't show up. So maybe they're not wrong, just that there are a lot of false positives? I know about the loading / saving issue, so it's not that.

**Comment by geekgirl101** [comment]
Yeah it seems to be predicting correctly now.  Good job. ^^

**Comment by agfor** [comment]
Next predicted train was correct as well.
